[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/auth/callback"
  to = "/.netlify/functions/auth-callback"
  status = 200
  force = true

[template.environment]
  SUPABASE_URL = "URL of your Supabase project"
  SUPABASE_SERVICE_ROLE_KEY = "Your Supabase service role key"
  SUPABASE_ANON_KEY = "Your Supabase anon/public key"
  VITE_SUPABASE_URL = "URL of your Supabase project"
  VITE_SUPABASE_ANON_KEY = "Your Supabase anon/public key"
